version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\ServiceCatalogApi
      dockerfile: Dockerfile
    environment: 
      DatabaseServer: mssqlserver
      DatabaseName: EventsDb
      DatabaseUser: sa
      DatabasePassword: Olive!123sql
      ExternalCatalogBaseUrl: http://localhost:7200
    ports:
      - "7200:80"
    container_name: eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: Y 
      SA_PASSWORD: Olive!123sql
    ports:
      - "11433:1433"
    container_name: eventssqlserver
    networks:
      - backend




